export const data = [
    {
        orderId: 'TBM1234567',
        tableNo: 1,
        customerName: 'Akash chandra',
        orderType: 'Delivery',
        orderStatus: 'New Order',
        payment: 'Paid',
    },
    {
        orderId: 'TBM1234567',
        tableNo: 2,
        customerName: 'Rahul Kumar',
        orderType: 'Dine In',
        orderStatus: 'Updated Order',
        payment: 'Un-Paid',
    },
    {
        orderId: 'TBM1234567',
        tableNo: 3,
        customerName: 'Judy Harris',
        orderType: 'Take Away',
        orderStatus: 'New Order',
        payment: 'Paid',
    },
    {
        orderId: 'TBM1234567',
        tableNo: 4,
        customerName: 'Monique Metz',
        orderType: 'Take Away',
        orderStatus: 'Updated Order',
        payment: 'Un-Paid',
    },
    {
        orderId: 'TBM1234567',
        tableNo: 5,
        customerName: 'Tim Mante',
        orderType: 'Take Away',
        orderStatus: 'New Order',
        payment: 'Paid',
    },
    {
        orderId: 'TBM1234567',
        tableNo: 6,
        customerName: 'Olga Gaylord',
        orderType: 'Take Away',
        orderStatus: 'New Order',
        payment: 'Un-Paid',
    },
    {
        orderId: 'TBM1234567',
        tableNo: 7,
        customerName: 'Rangabashiyam charak',
        orderType: 'Dine In',
        orderStatus: 'New Order',
        payment: 'Paid',
    },
    {
        orderId: 'TBM1234567',
        tableNo: 8,
        customerName: 'Rex Gorczany',
        orderType: 'Delivery',
        orderStatus: 'Updated Order',
        payment: 'Paid',
    },
    {
        orderId: 'TBM1234567',
        tableNo: 9,
        customerName: 'Palermo',
        orderType: 'Delivery',
        orderStatus: 'New Order',
        payment: 'Un-Paid',
    },
    {
        orderId: 'TBM1234567',
        tableNo: 10,
        customerName: 'Leo Tokyo',
        orderType: 'Take Away',
        orderStatus: 'Updated Order',
        payment: 'Paid',
    },
    {
        orderId: 'TBM1234567',
        tableNo: 11,
        customerName: 'Merry Jain',
        orderType: 'Dine In',
        orderStatus: 'New Order',
        payment: 'Paid',
    },
    {
        orderId: 'TBM1234567',
        tableNo: 12,
        customerName: 'Merry Jain',
        orderType: 'Dine In',
        orderStatus: 'New Order',
        payment: 'Un-Paid',
    },
    {
        orderId: 'TBM1234567',
        tableNo: 13,
        customerName: 'Merry Jain',
        orderType: 'Dine In',
        orderStatus: 'Updated Order',
        payment: 'Paid',
    },
    {
        orderId: 'TBM1234567',
        tableNo: 14,
        customerName: 'Merry Jain',
        orderType: 'Delivery',
        orderStatus: 'New Order',
        payment: 'Un-Paid',
    },
    {
        orderId: 'TBM1234567',
        tableNo: 15,
        customerName: 'Merry Jain',
        orderType: 'Delivery',
        orderStatus: 'Updated Order',
        payment: 'Un-Paid',
    },
]